2019-11-26 23:20:44.899 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-26 23:20:44.904 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-26 23:20:44.905 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-26 23:20:44.909 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-26 23:20:44.910 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-26 23:20:44.910 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-26 23:20:44.915 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-26 23:20:44.917 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-26 23:20:44.919 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-26 23:20:44.921 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-26 23:20:44.922 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-26 23:20:45.000 [warning] <0.294.0> lager_error_logger_h dropped 87 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-26 23:21:30.464 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-26 23:21:30.468 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-26 23:21:30.469 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-26 23:21:30.473 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-26 23:21:30.475 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-26 23:21:30.475 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-26 23:21:30.481 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-26 23:21:30.482 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-26 23:21:30.485 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-26 23:21:30.487 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-26 23:21:30.488 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-26 23:21:30.999 [warning] <0.286.0> lager_error_logger_h dropped 87 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-26 23:21:45.485 [error] <0.450.0> CRASH REPORT Process <0.450.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:400...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:21:45.519 [error] <0.288.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.449.0>,1,<0.450.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;...">>,...},...}},...},...},...},...},...]},...}}
2019-11-26 23:23:09.404 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-26 23:23:09.408 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-26 23:23:09.410 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-26 23:23:09.414 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-26 23:23:09.415 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-26 23:23:09.415 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-26 23:23:09.420 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-26 23:23:09.421 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-26 23:23:09.423 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-26 23:23:09.425 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-26 23:23:09.426 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-26 23:23:10.000 [warning] <0.288.0> lager_error_logger_h dropped 87 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-26 23:23:39.337 [error] <0.449.0> CRASH REPORT Process <0.449.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"host">> => <<"localhost:4000">>,<<"user-agent">> => <<"curl/7.65.3">>},host => <<"localhost">>,host_info => undefined,method => <<"POST">>,path => <<"/">>,path_info => undefined,peer => {{127,0,0,1},56294},pid => <0.448.0>,...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:23:39.358 [error] <0.290.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.448.0>,1,<0.449.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"host">> => <<"localhost:4000">>,<<"user-agent">> => <<"curl/7.65.3">>},host => <<"localhost">>,host_info => undefined,method => <<"POST">>,...}},...},...},...},...},...]},...}}
2019-11-26 23:23:50.010 [error] <0.453.0> CRASH REPORT Process <0.453.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"host">> => <<"localhost:4000">>,<<"user-agent">> => <<"curl/7.65.3">>},host => <<"localhost">>,host_info => undefined,method => <<"POST">>,path => <<"/api/">>,path_info => undefined,peer => {{127,0,0,1},56296},pid => <0.452.0>,...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:23:50.013 [error] <0.290.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.452.0>,1,<0.453.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"host">> => <<"localhost:4000">>,<<"user-agent">> => <<"curl/7.65.3">>},host => <<"localhost">>,host_info => undefined,method => <<"POST">>,...}},...},...},...},...},...]},...}}
2019-11-26 23:24:00.209 [error] <0.457.0> CRASH REPORT Process <0.457.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:400...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:24:00.212 [error] <0.290.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.456.0>,1,<0.457.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;...">>,...},...}},...},...},...},...},...]},...}}
2019-11-26 23:24:24.460 [error] <0.461.0> CRASH REPORT Process <0.461.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 3,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"content-length">> => <<"3">>,<<"content-type">> => <<"application/x-www-form-urlencoded">>,<<"host">> => <<"localhost:4000">>,<<"user-agent">> => <<"curl/7.65.3">>},host => <<"localhost">>,host_info => ...,...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:24:24.464 [error] <0.290.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.460.0>,1,<0.461.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 3,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"content-length">> => <<"3">>,<<"content-type">> => <<"application/x-www-form-urlencoded">>,<<"host">> => <<"localhost:...">>,...},...}},...},...},...},...},...]},...}}
2019-11-26 23:24:26.320 [error] <0.465.0> CRASH REPORT Process <0.465.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 3,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"content-length">> => <<"3">>,<<"content-type">> => <<"application/x-www-form-urlencoded">>,<<"host">> => <<"localhost:4000">>,<<"user-agent">> => <<"curl/7.65.3">>},host => <<"localhost">>,host_info => ...,...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:24:26.323 [error] <0.290.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.464.0>,1,<0.465.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 3,cert => undefined,has_body => true,has_read_body => true,headers => #{<<"accept">> => <<"*/*">>,<<"content-length">> => <<"3">>,<<"content-type">> => <<"application/x-www-form-urlencoded">>,<<"host">> => <<"localhost:...">>,...},...}},...},...},...},...},...]},...}}
2019-11-26 23:24:52.982 [error] <0.469.0> CRASH REPORT Process <0.469.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => init,message => nil,module => 'Elixir.ToyWeb.TracksController',reason => nil},[{'Elixir.ToyWeb.TracksController',init,[index],[]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.ToyWeb.Endpoint',plug_builder_call,2,[{file,"lib/toy_web/endpoint.ex"},{line,1}]},{'Elixir.ToyWeb.Endpoint','call (overridable 3)',2,[{file,"lib/plug/debugger.ex"},{line,122}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:24:52.984 [error] <0.290.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.468.0>,1,<0.469.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => init,message => nil,module => 'Elixir.ToyWeb.TracksController',reason => nil},[{'Elixir.ToyWeb.TracksController',init,[index],[]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.ToyWeb.Endpoint',plug_builder_call,2,[{file,"lib/toy_web/endpoint.ex"},{line,1}]},{'Elixir.ToyWeb.Endpoint',...},...]},...},...]},...}}
2019-11-26 23:24:55.345 [error] <0.473.0> CRASH REPORT Process <0.473.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => init,message => nil,module => 'Elixir.ToyWeb.TracksController',reason => nil},[{'Elixir.ToyWeb.TracksController',init,[index],[]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.ToyWeb.Endpoint',plug_builder_call,2,[{file,"lib/toy_web/endpoint.ex"},{line,1}]},{'Elixir.ToyWeb.Endpoint','call (overridable 3)',2,[{file,"lib/plug/debugger.ex"},{line,122}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:24:55.348 [error] <0.290.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.472.0>,1,<0.473.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => init,message => nil,module => 'Elixir.ToyWeb.TracksController',reason => nil},[{'Elixir.ToyWeb.TracksController',init,[index],[]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.ToyWeb.Endpoint',plug_builder_call,2,[{file,"lib/toy_web/endpoint.ex"},{line,1}]},{'Elixir.ToyWeb.Endpoint',...},...]},...},...]},...}}
2019-11-26 23:25:06.680 [error] <0.477.0> CRASH REPORT Process <0.477.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"connection">> => <<"keep-alive">>,<<"host">> => <<"localhost:400...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:25:06.684 [error] <0.290.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.476.0>,1,<0.477.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;...">>,...},...}},...},...},...},...},...]},...}}
2019-11-26 23:25:25.359 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-26 23:25:25.363 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-26 23:25:25.364 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-26 23:25:25.368 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-26 23:25:25.369 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-26 23:25:25.369 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-26 23:25:25.374 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-26 23:25:25.375 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-26 23:25:25.377 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-26 23:25:25.379 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-26 23:25:25.380 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-26 23:25:26.000 [warning] <0.288.0> lager_error_logger_h dropped 87 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-26 23:25:28.201 [error] <0.449.0> CRASH REPORT Process <0.449.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => init,message => nil,module => 'Elixir.ToyWeb.TracksController',reason => nil},[{'Elixir.ToyWeb.TracksController',init,[index],[]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.ToyWeb.Endpoint',plug_builder_call,2,[{file,"lib/toy_web/endpoint.ex"},{line,1}]},{'Elixir.ToyWeb.Endpoint','call (overridable 3)',2,[{file,"lib/plug/debugger.ex"},{line,122}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:25:28.236 [error] <0.290.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.448.0>,1,<0.449.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => init,message => nil,module => 'Elixir.ToyWeb.TracksController',reason => nil},[{'Elixir.ToyWeb.TracksController',init,[index],[]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.ToyWeb.Endpoint',plug_builder_call,2,[{file,"lib/toy_web/endpoint.ex"},{line,1}]},{'Elixir.ToyWeb.Endpoint',...},...]},...},...]},...}}
2019-11-26 23:25:29.056 [error] <0.454.0> CRASH REPORT Process <0.454.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => init,message => nil,module => 'Elixir.ToyWeb.TracksController',reason => nil},[{'Elixir.ToyWeb.TracksController',init,[index],[]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.ToyWeb.Endpoint',plug_builder_call,2,[{file,"lib/toy_web/endpoint.ex"},{line,1}]},{'Elixir.ToyWeb.Endpoint','call (overridable 3)',2,[{file,"lib/plug/debugger.ex"},{line,122}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:25:29.059 [error] <0.290.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.453.0>,1,<0.454.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => init,message => nil,module => 'Elixir.ToyWeb.TracksController',reason => nil},[{'Elixir.ToyWeb.TracksController',init,[index],[]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.ToyWeb.Endpoint',plug_builder_call,2,[{file,"lib/toy_web/endpoint.ex"},{line,1}]},{'Elixir.ToyWeb.Endpoint',...},...]},...},...]},...}}
2019-11-26 23:25:30.180 [error] <0.457.0> CRASH REPORT Process <0.457.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => init,message => nil,module => 'Elixir.ToyWeb.TracksController',reason => nil},[{'Elixir.ToyWeb.TracksController',init,[index],[]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.ToyWeb.Endpoint',plug_builder_call,2,[{file,"lib/toy_web/endpoint.ex"},{line,1}]},{'Elixir.ToyWeb.Endpoint','call (overridable 3)',2,[{file,"lib/plug/debugger.ex"},{line,122}]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:25:30.183 [error] <0.290.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.453.0>,2,<0.457.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => init,message => nil,module => 'Elixir.ToyWeb.TracksController',reason => nil},[{'Elixir.ToyWeb.TracksController',init,[index],[]},{'Elixir.Phoenix.Router','__call__',2,[{file,"lib/phoenix/router.ex"},{line,288}]},{'Elixir.ToyWeb.Endpoint',plug_builder_call,2,[{file,"lib/toy_web/endpoint.ex"},{line,1}]},{'Elixir.ToyWeb.Endpoint',...},...]},...},...]},...}}
2019-11-26 23:26:16.681 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-26 23:26:16.685 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-26 23:26:16.687 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-26 23:26:16.691 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-26 23:26:16.692 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-26 23:26:16.692 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-26 23:26:16.697 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-26 23:26:16.699 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-26 23:26:16.701 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-26 23:26:16.703 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-26 23:26:16.704 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-26 23:26:16.999 [warning] <0.294.0> lager_error_logger_h dropped 87 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-26 23:26:22.595 [error] <0.455.0> CRASH REPORT Process <0.455.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"cache-control">> => <<"max-age=0">>,<<"connection">> => <<"keep-...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:26:22.635 [error] <0.296.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.454.0>,1,<0.455.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;...">>,...},...}},...},...},...},...},...]},...}}
2019-11-26 23:26:24.257 [error] <0.460.0> CRASH REPORT Process <0.460.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;q=0.5">>,<<"cache-control">> => <<"max-age=0">>,<<"connection">> => <<"keep-...">>,...},...}},...},...},...},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:26:24.260 [error] <0.296.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.459.0>,1,<0.460.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate">>,<<"accept-language">> => <<"en-US,en;...">>,...},...}},...},...},...},...},...]},...}}
2019-11-26 23:26:38.795 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-26 23:26:38.799 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-26 23:26:38.801 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-26 23:26:38.805 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-26 23:26:38.806 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-26 23:26:38.806 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-26 23:26:38.811 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-26 23:26:38.813 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-26 23:26:38.815 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-26 23:26:38.817 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-26 23:26:38.818 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-26 23:26:39.001 [warning] <0.288.0> lager_error_logger_h dropped 87 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-26 23:26:41.105 [error] <0.449.0> CRASH REPORT Process <0.449.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => encode,message => nil,module => 'Elixir.Poison',reason => nil},[{'Elixir.Poison',encode,[#{}],[]},{'Elixir.ToyWeb.TracksController',index,2,[{file,"lib/toy_web/controllers/track_controllers.ex"},{line,5}]},{'Elixir.ToyWeb.TracksController',action,2,[{file,"lib/toy_web/controllers/track_controllers.ex"},{line,1}]},{'Elixir.ToyWeb.TracksController',phoenix_controller_pipeline,2,[{file,"lib/toy_..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:26:41.130 [error] <0.290.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.448.0>,1,<0.449.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => encode,message => nil,module => 'Elixir.Poison',reason => nil},[{'Elixir.Poison',encode,[#{}],[]},{'Elixir.ToyWeb.TracksController',index,2,[{file,"lib/toy_web/controllers/track_controllers.ex"},{line,5}]},{'Elixir.ToyWeb.TracksController',action,2,[{file,"lib/toy_web/controllers/track_controllers.ex"},{line,1}]},{'Elixir.ToyWeb.TracksController',...},...]},...},...]},...}}
2019-11-26 23:26:42.677 [error] <0.452.0> CRASH REPORT Process <0.452.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => encode,message => nil,module => 'Elixir.Poison',reason => nil},[{'Elixir.Poison',encode,[#{}],[]},{'Elixir.ToyWeb.TracksController',index,2,[{file,"lib/toy_web/controllers/track_controllers.ex"},{line,5}]},{'Elixir.ToyWeb.TracksController',action,2,[{file,"lib/toy_web/controllers/track_controllers.ex"},{line,1}]},{'Elixir.ToyWeb.TracksController',phoenix_controller_pipeline,2,[{file,"lib/toy_..."},...]},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:26:42.679 [error] <0.290.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.448.0>,2,<0.452.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => encode,message => nil,module => 'Elixir.Poison',reason => nil},[{'Elixir.Poison',encode,[#{}],[]},{'Elixir.ToyWeb.TracksController',index,2,[{file,"lib/toy_web/controllers/track_controllers.ex"},{line,5}]},{'Elixir.ToyWeb.TracksController',action,2,[{file,"lib/toy_web/controllers/track_controllers.ex"},{line,1}]},{'Elixir.ToyWeb.TracksController',...},...]},...},...]},...}}
2019-11-26 23:30:13.087 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-26 23:30:13.091 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-26 23:30:13.093 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-26 23:30:13.096 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-26 23:30:13.097 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-26 23:30:13.097 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-26 23:30:13.103 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-26 23:30:13.104 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-26 23:30:13.106 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-26 23:30:13.109 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-26 23:30:13.110 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-26 23:30:13.999 [warning] <0.284.0> lager_error_logger_h dropped 87 messages in the last second that exceeded the limit of 50 messages/sec
2019-11-26 23:30:19.192 [error] <0.445.0> CRASH REPORT Process <0.445.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.ToyWeb.Worker',reason => nil},[{'Elixir.ToyWeb.Worker',publish,[<<"{}">>],[]},{'Elixir.ToyWeb.TracksController',index,2,[{file,"lib/toy_web/controllers/track_controllers.ex"},{line,6}]},{'Elixir.ToyWeb.TracksController',action,2,[{file,"lib/toy_web/controllers/track_controllers.ex"},{line,1}]},{'Elixir.ToyWeb.TracksController',phoenix_controller_pipeline,...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:30:19.214 [error] <0.286.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.444.0>,1,<0.445.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.ToyWeb.Worker',reason => nil},[{'Elixir.ToyWeb.Worker',publish,[<<"{}">>],[]},{'Elixir.ToyWeb.TracksController',index,2,[{file,"lib/toy_web/controllers/track_controllers.ex"},{line,6}]},{'Elixir.ToyWeb.TracksController',action,2,[{file,"lib/toy_web/controllers/track_controllers..."},...]},...]},...},...]},...}}
2019-11-26 23:30:21.170 [error] <0.448.0> CRASH REPORT Process <0.448.0> with 0 neighbours exited with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.ToyWeb.Worker',reason => nil},[{'Elixir.ToyWeb.Worker',publish,[<<"{}">>],[]},{'Elixir.ToyWeb.TracksController',index,2,[{file,"lib/toy_web/controllers/track_controllers.ex"},{line,6}]},{'Elixir.ToyWeb.TracksController',action,2,[{file,"lib/toy_web/controllers/track_controllers.ex"},{line,1}]},{'Elixir.ToyWeb.TracksController',phoenix_controller_pipeline,...},...]},...} in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59 in 'Elixir.Phoenix.Endpoint.Cowboy2Handler':init/4 line 59
2019-11-26 23:30:21.172 [error] <0.286.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,['Elixir.ToyWeb.Endpoint.HTTP',<0.444.0>,2,<0.448.0>,{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => publish,message => nil,module => 'Elixir.ToyWeb.Worker',reason => nil},[{'Elixir.ToyWeb.Worker',publish,[<<"{}">>],[]},{'Elixir.ToyWeb.TracksController',index,2,[{file,"lib/toy_web/controllers/track_controllers.ex"},{line,6}]},{'Elixir.ToyWeb.TracksController',action,2,[{file,"lib/toy_web/controllers/track_controllers..."},...]},...]},...},...]},...}}
2019-11-26 23:33:53.556 [info] <0.43.0> Application lager started on node nonode@nohost
2019-11-26 23:33:53.561 [info] <0.43.0> Application xmerl started on node nonode@nohost
2019-11-26 23:33:53.562 [info] <0.43.0> Application jsx started on node nonode@nohost
2019-11-26 23:33:53.566 [info] <0.43.0> Application ranch started on node nonode@nohost
2019-11-26 23:33:53.567 [info] <0.43.0> Application recon started on node nonode@nohost
2019-11-26 23:33:53.567 [info] <0.43.0> Application rabbit_common started on node nonode@nohost
2019-11-26 23:33:53.572 [info] <0.43.0> Application amqp_client started on node nonode@nohost
2019-11-26 23:33:53.574 [info] <0.43.0> Application amqp started on node nonode@nohost
2019-11-26 23:33:53.576 [info] <0.43.0> Application cowlib started on node nonode@nohost
2019-11-26 23:33:53.578 [info] <0.43.0> Application cowboy started on node nonode@nohost
2019-11-26 23:33:53.579 [info] <0.43.0> Application plug_cowboy started on node nonode@nohost
2019-11-26 23:33:54.000 [warning] <0.285.0> lager_error_logger_h dropped 87 messages in the last second that exceeded the limit of 50 messages/sec
